### ISSUE TITLE
Port forwarding not working on Mac OS 10 Yosemite

### ISSUE THREAD

**Issue by alberto56** [alberto56/vagrant-jenkins#23]
[this article](https://www.danpurdy.co.uk/web-development/osx-yosemite-port-forwarding-for-vagrant/) explains why.

**Comment by patrickdaulie** [comment]
After the setup I try to open http://localhost:8082, it looks like it's loading, but then the browser reports 'Failed to open page'. Looks like the webserver is ok, because it opens at http://localhost:8082 and displays Index of: /

I started jenkins with sudo /etc/init.d/jenkins start
and tried netstat

sudo netstat -tnlp | grep 8080
tcp        0      0 :::8080                     :::*                        LISTEN      7095/java

My client is Mas OSX Yosemite.

Any ideas ?

Thank you !
